### ISSUE TITLE
Summary of executed tasks does not include failed count

### ISSUE THREAD

**Issue by pushkargupta9807** [microsoft/lage#491]
**Describe the bug**

Summary of executed tasks does not include failed count

**To Reproduce**
Execute any list of tasks and at the end observe the summary line displaying the counts of success, pending etc and observe that failed count is missing. 

Example: 
[Tasks Count] success: 0, skipped: 219, pending: 0, aborted: 0

**Comment by kenotron** [comment]
Fixed in #331!
