### ISSUE TITLE
Documentation for v2 but install instructions for v1

### ISSUE THREAD

**Issue by drjonnicholson** [microsoft/lage#506]
**Describe the bug**
Published documentation is for v2.x, but installation steps are for v1.x

**To Reproduce**
For example:
1. Go to https://microsoft.github.io/lage/docs/Tutorial/installation
2. It says to install `"lage": "latest"` / do `npx lage init`
3. But pages like https://microsoft.github.io/lage/docs/Reference/config and https://microsoft.github.io/lage/docs/Cookbook/make-jest-fast are describing version 2 (`@lage-run/lage`) features

**Expected behavior**
Documentation should be consistently and clearly versioned. I didn't realise there was a version 2 released until I looked at the migration guide and then realised I had been trying to write a v2 config for v1 package. The cookbook examples do have a version 2 tag, but the configuration page doesn't.

Questions:
- Given #373, is v2 ready for general consumption?
- I'm just starting to build a new monorepo, should I build on v1 or v2?
- If I build on v2, what (if any) features are missing compared to v1?
- If I build on v2, how will I know when I need to switch the dependency back from `@lage-run/lage` to `lage`?

**Environment/Troubleshooting**
N/A

**Comment by kenotron** [comment]
v2 now is the latest in lage! yay! took a bit longer for me to get there... I wanted Microsoft Teams & Loop to be on v2 before really calling it `latest`. We'll need a guide for migration still!

**Comment by kenotron** [comment]
Didn't mean to the "Close with comment" button... just a comment!

**Comment by drjonnicholson** [comment]
Fantastic stuff! Just updated my reference to `@lage-run/lage` to `lage` and all initially looked good.

Have found that my workers for testing and linting, based on the cookbook examples, no longer work. I get the following error:
```
thread '<unnamed>' panicked at 'Failed to read file: Failed to read file', src\hasher.rs:87:48
stack backtrace:
   0:     0x7ffeec147d45 - napi_register_module_v1
   1:     0x7ffeec04773b - <unknown>
   2:     0x7ffeec13a7b1 - napi_register_module_v1
   3:     0x7ffeec14a24b - napi_register_module_v1
   4:     0x7ffeec149e07 - napi_register_module_v1
   5:     0x7ffeec14adbb - napi_register_module_v1
   6:     0x7ffeec14a7f6 - napi_register_module_v1
   7:     0x7ffeec14a749 - napi_register_module_v1
   8:     0x7ffeec14a734 - napi_register_module_v1
   9:     0x7ffeec14e255 - napi_register_module_v1
  10:     0x7ffeec14e5b6 - napi_register_module_v1
  11:     0x7ffeec0560c4 - <unknown>
  12:     0x7ffeec064475 - <unknown>
  13:     0x7ffeec15aae6 - napi_register_module_v1
  14:     0x7ffeec0c9510 - napi_register_module_v1
  15:     0x7ffeec0c81fc - napi_register_module_v1
  16:     0x7ffeec14714b - napi_register_module_v1
  17:     0x7fff42b9269d - BaseThreadInitThunk
  18:     0x7fff44cca9f8 - RtlUserThreadStart
```

Have tried both 2.6.0 and 2.6.1.

The worker might be as simple as logging some text to the console, but it just falls over :(

**Comment by drjonnicholson** [comment]
Have opened a new issue for the rust issue, v2.5.6 appears to work so far though
