### ISSUE TITLE
lage v2 --verbose broken?

### ISSUE THREAD

**Issue by dzearing** [microsoft/lage#557]
Expected:

Passing `--verbose` logs without the fancy reporting, with starts/stops that are suitable for a CI workflow.

Resulted:

Still fancy reporting.

**Comment by JasonGore** [comment]
I just came here to enter same issue! I see the same thing, `--verbose` doesn't seem to have any effect on lage v2 output.

**Comment by JasonGore** [comment]
This is for version `@lage-run/lage` 2.5.30.

**Comment by JasonGore** [comment]
Workaround: `--reporter old --verbose`

**Comment by kenotron** [comment]
I just fixed it in the latest 2.5.34!!
