### ISSUE TITLE
Invert --no-deps flag to be default on scoped execution

### ISSUE THREAD

**Issue by oliwheeler** [microsoft/lage#72]
According to [the docs](https://microsoft.github.io/lage/guide/scopes.html#scoped-builds-with-no-dependent-their-dependencies), the task will run on the dependants of the scoped packages unless the `--no-deps` flag is passed.

It would be nicer if this was inverted so that the default case was to run the tasks *excluding* dependants and have a flag, say `--include-dependants` to run the task for dependants.

This would save typing for developers when running tasks in their local dev loop.
The `--include-dependants` flag can be used in CI scripts.

**Comment by kenotron** [comment]
So we added a new flag called "--to" that does both at the same time. This preserves the behavior and actually becomes a nice syntactic sugar.
