### ISSUE TITLE
Consider using SIGTERM for terminating jobs that are running

### ISSUE THREAD

**Issue by kenotron** [microsoft/lage#81]
When one task fails, all the other tasks get a SIGKILL. which leaves the children of these processes orphans, this means that the lage command is finished but there is still some processes working on the repo. Sending a SIGTERM may be more correct as processes will get a chance to propagate the SIGNAL to their children.

If process didn't die in 5s, send SIGKILL.

**Comment by kenotron** [comment]
Actually, the correct signal to send is SIGTERM, instead of SIGINT. 

https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html

**Comment by VincentBailly** [comment]
I noticed that when a task hanged, sending SIGINT would kill all the children but not SIGTERM
