### ISSUE TITLE
--since flag does not behave well for changes in global files

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/lage#88]
Scenario 1:
  - I have a change to an RFC file
  - expected behavior: Lage builds nothing
  - current behavior: Lage builds everything

Scenario 2:
  - I have a change to a global config file and a file in the package `foo`
  - expected behavior: Lage builds everything
  - current behavior: Lage builds is scoped to `foo`

**Comment by kenotron** [comment]
To address this, you should be using the `lage.config.js`'s `ignore` option:

https://microsoft.github.io/lage/guide/config.html#ignore

It's not too obvious and the documentation style needs to be updated probably to make this stand out more.

**Comment by kenotron** [comment]
To address Scenario 2, you should be using the `lage.config.js`'s `repoWideChanges` option:

https://microsoft.github.io/lage/guide/config.html#repowidechanges

It's again, not too obvious maybe? I welcome feedback on naming (maybe put this under a section called "scope:" in the lage.config.js itself.

**Comment by kenotron** [comment]
Please feel free to suggestion better config scheme, but I'm going to close this one for now since I've added features to address both scenarios.
