### ISSUE TITLE
Feature request: custom profile file name and path

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/lage#94]
Add an option so I can give a custom path and name to the profile file generated by Lage

**Comment by oliwheeler** [comment]
Here are two suggestions for how lage could parse the option:

### Pass an optional argument to profile flag
```sh
lage build --profile path/to/profile.json
```

If no path is provided, behavior would be the same as it is now (write to tmp dir)

### Add `--profile-path` flag

This flag would only apply if the `--profile` flag is also set
```sh
lage build --profile --profile-path path/to/profile.json
```

I prefer the first approach

**Comment by kenotron** [comment]
I like the 1st approach as well from @oliwheeler's suggestion.
