### ISSUE TITLE
Feature request: make --scope flag support glob

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/lage#95]
Context: I have the following packages in my repo:

A-1, A-2, B, C, D

The two following commands should be identical:
`lage build --scope {A-*,B}`

and
`lage build --scope A-1 --scope A-2 --scope B`

**Comment by kenotron** [comment]
We can currently do:

`lage build --scope A-* --scope B` 

via this: https://www.npmjs.com/package/matcher

is that sufficient?

**Comment by kenotron** [comment]
Alright, the implementation is actually in workspace-tools, so I'll add it there.
